(module
  (func (export "select") (param i32) (result i32)
    (i32.const 1)
    (i32.const 0)
    (local.get 0)
    (select)
  )

  (func (export "select2") (param i32) (result i32)
    (i32.const 0)
    (i32.const 0)
    (local.get 0)
    (select)
  )
)
